import typing

import numpy as np

from clypto.hints.sense import SenseType

class Agent:
    solution: typing.Any
    @property
    def objectives(self) -> np.ndarray | None: ...
    @property
    def fitness(self) -> float: ...
    @property
    def weights(self) -> typing.Any: ...

    def __init__(self, solution: typing.Any = ..., objectives: typing.Any = ..., weights: typing.Any = ..., **fields: typing.Any) -> None: ...
    def evaluate(self, problem: typing.Any) -> typing.Self: ...
    def update_solution(self, other: Agent, solution: typing.Any = ...) -> None: ...
    def copy(self) -> typing.Self: ...
    def update(self, **fields: typing.Any) -> None: ...
    def __float__(self) -> float: ...

def duplicate_agent(agent: Agent) -> Agent: ...
def sync_if_duplicate(that: Agent, other: Agent) -> bool: ...
def better_fitness(x: float, y: float, sense: SenseType) -> bool: ...
def is_better(x: Agent, y: Agent, sense: SenseType) -> bool: ...
def get_better_agent(x: Agent, y: Agent, sense: SenseType = ..., reverse: bool = ...) -> Agent: ...
def argsort_agents(agents: typing.Sequence[Agent], sense: SenseType) -> list[int]: ...
def sort_agents(agents: typing.Sequence[Agent], sense: SenseType) -> list[Agent]: ...
def greedy_agents(old: typing.Sequence[Agent], new: typing.Sequence[Agent], sense: SenseType) -> list[Agent]: ...
