import typing

from clypto.hints.sense import SenseType

class LegacyAgent:
    solution: typing.Any
    target: typing.Any

    def __init__(self, solution: typing.Any = ..., target: typing.Any = ..., **fields: typing.Any) -> None: ...
    def copy(self) -> typing.Self: ...
    def update(self, **fields: typing.Any) -> None: ...
    def __float__(self) -> float: ...

class LegacyNativeAgent(LegacyAgent): ...

def duplicate_agent(agent: typing.Any) -> typing.Any: ...
def sync_if_duplicate(that: typing.Any, other: typing.Any) -> bool: ...
def compare_fitness(that: typing.Any, other: typing.Any, sense: SenseType = ...) -> int: ...
def get_better_solution(that: typing.Any, other: typing.Any, sense: SenseType = ...) -> typing.Any: ...
def is_better_than(that: typing.Any, other: typing.Any, sense: SenseType = ...) -> bool: ...
