import typing

from clypto.hints.array import NDArrayType
from clypto.hints.sense import SenseType
from clypto.utils.target import Target

class BaseAgent:
    # Every concrete agent (AgentStatic, AgentDynamic) carries these two fields --
    # it's the core "agent = [solution, target]" contract used throughout the
    # optimizer/algorithm code, including generic BaseAgent-typed collections in
    # Optimizer's static utility methods (get_sorted_population, etc.). BaseAgent
    # itself is never instantiated (every method below raises NotImplementedError),
    # so declaring them here is purely for static analysis and has no runtime effect.
    #
    # Declared non-Optional (rather than matching the Optional default __init__
    # accepts) for the same reason as Optimizer.problem/pop/g_best in classic.py:
    # solution/target are None only during agent construction itself
    # (generate_empty_agent -> generate_agent, both in classic.py); by the time an
    # agent is placed in a population and any of the ~150 algorithms' evolve()
    # methods read it, both are always set.
    solution: NDArrayType
    target: Target

    def copy(self) -> "BaseAgent": ...
    def update_agent(
        self, solution: NDArrayType, target: Target
    ) -> None: ...
    def update(self, *args: typing.Any, **kwargs: typing.Any) -> None: ...
    def sync_if_duplicate(self, other: "BaseAgent") -> bool: ...
    def _compare_fitness(
        self, other: "BaseAgent", minmax: SenseType = ...
    ) -> int: ...
    def get_better_solution(
        self, other: "BaseAgent", minmax: SenseType = ...
    ) -> "BaseAgent": ...
    def is_better_than(
        self, other: "BaseAgent", minmax: SenseType = ...
    ) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: typing.Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __float__(self) -> float: ...

class AgentStatic(BaseAgent):
    def __init__(
        self,
        solution: typing.Optional[NDArrayType] = ...,
        target: typing.Optional[Target] = ...,
    ) -> None: ...
    def copy(self) -> "AgentStatic": ...
    def get_better_solution(
        self, other: "BaseAgent", minmax: SenseType = ...
    ) -> "AgentStatic": ...

class AgentDynamic(BaseAgent):
    def __init__(
        self,
        solution: typing.Optional[NDArrayType] = ...,
        target: typing.Optional[Target] = ...,
        **kwargs: typing.Any,
    ) -> None: ...
    def __getattr__(self, name: str) -> typing.Any: ...
    def copy(self) -> "BaseAgent": ...
