import typing

from clypto.hints.array import NDArrayType
from clypto.hints.sense import SenseType
from clypto.utils.target import Target

class _LegacyAgent:
    solution: NDArrayType
    target: Target

    def __init__(
        self,
        solution: typing.Optional[NDArrayType] = ...,
        target: typing.Optional[Target] = ...,
    ) -> None: ...
    def copy(self) -> "_LegacyAgent": ...
    def update_agent(self, solution: NDArrayType, target: Target) -> None: ...
    def update(self, **kwargs: typing.Any) -> None: ...
    def sync_if_duplicate(self, other: "_LegacyAgent") -> bool: ...
    def _compare_fitness(self, other: "_LegacyAgent", minmax: SenseType = ...) -> int: ...
    def get_better_solution(
        self, other: "_LegacyAgent", minmax: SenseType = ...
    ) -> "_LegacyAgent": ...
    def is_better_than(self, other: "_LegacyAgent", minmax: SenseType = ...) -> bool: ...
    def __repr__(self) -> str: ...
    def __eq__(self, other: typing.Any) -> bool: ...
    def __hash__(self) -> int: ...
    def __float__(self) -> float: ...
