import typing

import numpy as np
import numpy.typing as npt

from clypto.utils.target import Target


class BaseAgent(typing.Protocol):
    solution: npt.NDArray[np.number] | None
    target: Target | None

    def copy(self): ...

    def update_agent(self, solution: np.ndarray, target: Target): ...

    def update(self, **kwargs) -> None: ...

    def sync_if_duplicate(self, other: "BaseAgent") -> bool: ...

    def _compare_fitness(self, other: "BaseAgent", minmax: str = "min") -> int: ...

    def get_better_solution(self, other: "BaseAgent", minmax: str = "min") -> "BaseAgent": ...

    def is_better_than(self, other: "BaseAgent", minmax: str = "min") -> bool: ...

    def __repr__(self): ...

    def __eq__(self, other): ...

    def __hash__(self): ...

    def __float__(self) -> float: ...
