#!/usr/bin/env python
# Created by "Thieu" at 22:07, 07/04/2020 ----------%
#       Email: nguyenthieu2102@gmail.com            %
#       Github: https://github.com/thieu1995        %
# --------------------------------------------------%

import numpy as np
cimport clypto.core as cy



cdef class OriginalFA(cy.Optimizer):
    """
    The original version of: Fireworks Algorithm (FA)

    Links:
        1. https://doi.org/10.1007/978-3-642-13495-1_44

    Hyper-parameters should fine-tune in approximate range to get faster convergence toward the global optimum:
        + max_sparks (int): parameter controlling the total number of sparks generated by the pop_size fireworks, default=100
        + p_a (float): percent (const parameter), default=0.04
        + p_b (float): percent (const parameter), default=0.8
        + max_ea (int): maximum explosion amplitude, default=40
        + m_sparks (int): number of sparks generated in each explosion generation, default=100

    Examples
    ~~~~~~~~
    >>> from clypto.native.collection.swarm_based import FA    >>> import numpy as np
    >>> from clypto import NumberBounds
    >>>
    >>> def objective_function(solution):
    >>>     return np.sum(solution**2)
    >>>
    >>> problem_dict = {
    >>>     "bounds": NumberBounds(float, low=(-10.,) * 30, up=(10.,) * 30, name="delta"),
    >>>     "sense": "min",
    >>>     "obj_func": objective_function
    >>> }
    >>>
    >>> model = FA.OriginalFA(epoch=1000, pop_size=50, max_sparks = 50, p_a = 0.04, p_b = 0.8, max_ea = 40, m_sparks = 50)
    >>> g_best = model.solve(problem_dict)
    >>> print(f"Solution: {g_best.solution}, Fitness: {g_best.fitness}")
    >>> print(f"Solution: {model.g_best.solution}, Fitness: {model.g_best.fitness}")

    References
    ~~~~~~~~~~
    [1] Tan, Y. and Zhu, Y., 2010, June. Fireworks algorithm for optimization. In International
    conference in swarm intelligence (pp. 355-364). Springer, Berlin, Heidelberg.
    """

    cdef public int m_sparks
    cdef public int max_ea
    cdef public int max_sparks
    cdef public double p_a
    cdef public double p_b

    def __init__(
            self,
            epoch: int = 10000,
            pop_size: int = 100,
            max_sparks: int = 100,
            p_a: float = 0.04,
            p_b: float = 0.8,
            max_ea: int = 40,
            m_sparks: int = 100,
            **kwargs: object
    ) -> None:
        """
        Args:
            epoch (int): maximum number of iterations, default = 10000
            pop_size (int): number of population size, default = 100
            max_sparks (int): parameter controlling the total number of sparks generated by the pop_size fireworks, default=100
            p_a (float): percent (const parameter), default=0.04
            p_b (float): percent (const parameter), default=0.8
            max_ea (int): maximum explosion amplitude, default=40
            m_sparks (int): number of sparks generated in each explosion generation, default=100
        """
        super().__init__(parameters=["epoch", "pop_size", "max_sparks", "p_a", "p_b", "max_ea", "m_sparks"], sort_flag=False, **kwargs)
        self.epoch = cy.validator(int, epoch, [1, 100000], "epoch")
        self.population = cy.population(pop_size)
        self.max_sparks = cy.validator(int, max_sparks, [2, 10000], "max_sparks")
        self.p_a = cy.validator(float, p_a, (0, 1.0), "p_a")
        self.p_b = cy.validator(float, p_b, (0, 1.0), "p_b")
        self.max_ea = cy.validator(int, max_ea, [2, 100], "max_ea")
        self.m_sparks = cy.validator(int, m_sparks, [2, 10000], "m_sparks")

    cdef void evolve(self, int epoch):
        """
        The main operations (equations) of algorithm. Inherit from LegacyOptimizer class

        Args:
            epoch (int): The current iteration
        """
        pop_size = self.population.size()
        fit_list = np.array([agent.fitness for agent in self.population])
        fit_list = sorted(fit_list)
        pop_new = []
        for idx in range(0, pop_size):
            si = (
                    self.max_sparks
                    * (fit_list[-1] - self.population[idx].fitness)
                    / (pop_size * fit_list[-1] - np.sum(fit_list) + self.EPSILON)
            )
            Ai = (
                    self.max_ea
                    * (self.population[idx].fitness - fit_list[0])
                    / (np.sum(fit_list) - fit_list[0] + self.EPSILON)
            )
            if si < self.p_a * self.max_sparks:
                si_ = int(round(self.p_a * self.max_sparks) + 1)
            elif si > self.p_b * self.m_sparks:
                si_ = int(round(self.p_b * self.max_sparks) + 1)
            else:
                si_ = int(round(si) + 1)
            ## Algorithm 1
            pop_new = []
            for j in range(0, si_):
                x = self.population[idx].solution.copy()
                list_idx = self.generator.choice(
                    range(0, self.problem.n_dims),
                    round(self.generator.uniform() * self.problem.n_dims),
                    replace=False,
                )
                displacement = Ai * self.generator.uniform(-1, 1)
                x[list_idx] = x[list_idx] + displacement
                x = np.where(
                    np.logical_or(x < self.problem.bounds.low, x > self.problem.bounds.up),
                    self.problem.bounds.low
                    + np.abs(x) % (self.problem.bounds.up - self.problem.bounds.low),
                    x,
                )
                x = cy.correct_solution(self.problem, x)
                agent = self.population.create_agent(x)
                pop_new.append(agent)
            pop_new = self.population.evaluate(pop_new, self.mode)

        for _ in range(0, self.m_sparks):
            idx = self.generator.integers(0, pop_size)
            x = self.population[idx].solution.copy()
            list_idx = self.generator.choice(
                range(0, self.problem.n_dims),
                round(self.generator.uniform() * self.problem.n_dims),
                replace=False,
            )
            x[list_idx] = x[list_idx] + self.generator.normal(
                0, 1, len(list_idx)
            )  # Gaussian
            condition = np.logical_or(
                x < self.problem.bounds.low, x > self.problem.bounds.up
            )
            pos_true = self.problem.bounds.low + np.abs(x) % (
                    self.problem.bounds.up - self.problem.bounds.low
            )
            x = np.where(condition, pos_true, x)
            x = cy.correct_solution(self.problem, x)
            agent = self.population.create_agent(x)
            pop_new.append(agent)
        pop_new = self.population.evaluate(pop_new, self.mode)

        ## Update the global best
        self.population = self.population.spawn(cy.sort_agents(pop_new + self.population, self.problem.sense)[:pop_size])
