#!/usr/bin/env python
# Created by "Thieu" at 22:07, 07/04/2020 ----------%
#       Email: nguyenthieu2102@gmail.com            %
#       Github: https://github.com/thieu1995        %
# --------------------------------------------------%

import numpy as np
from clypto.optimizer._native cimport utils as cy
from clypto.optimizer._native import ops
from clypto.optimizer._native.optimizer cimport LegacyNativeOptimizer
from clypto.optimizer._native.population cimport NativePopulation


cdef class OriginalFA(LegacyNativeOptimizer):
    """
    The original version of: Fireworks Algorithm (FA)

    Links:
        1. https://doi.org/10.1007/978-3-642-13495-1_44

    Hyper-parameters should fine-tune in approximate range to get faster convergence toward the global optimum:
        + max_sparks (int): parameter controlling the total number of sparks generated by the pop_size fireworks, default=100
        + p_a (float): percent (const parameter), default=0.04
        + p_b (float): percent (const parameter), default=0.8
        + max_ea (int): maximum explosion amplitude, default=40
        + m_sparks (int): number of sparks generated in each explosion generation, default=100

    Examples
    ~~~~~~~~
    >>> from clypto.collection.swarm_based import FA    >>> import numpy as np
    >>> from clypto import FloatVar
    >>>
    >>> def objective_function(solution):
    >>>     return np.sum(solution**2)
    >>>
    >>> problem_dict = {
    >>>     "bounds": FloatVar(lb=(-10.,) * 30, ub=(10.,) * 30, name="delta"),
    >>>     "minmax": "min",
    >>>     "obj_func": objective_function
    >>> }
    >>>
    >>> model = FA.OriginalFA(epoch=1000, pop_size=50, max_sparks = 50, p_a = 0.04, p_b = 0.8, max_ea = 40, m_sparks = 50)
    >>> g_best = model.solve(problem_dict)
    >>> print(f"Solution: {g_best.solution}, Fitness: {g_best.target.fitness}")
    >>> print(f"Solution: {model.g_best.solution}, Fitness: {model.g_best.target.fitness}")

    References
    ~~~~~~~~~~
    [1] Tan, Y. and Zhu, Y., 2010, June. Fireworks algorithm for optimization. In International
    conference in swarm intelligence (pp. 355-364). Springer, Berlin, Heidelberg.
    """

    cdef public object max_sparks
    cdef public object p_a
    cdef public object p_b
    cdef public object max_ea
    cdef public object m_sparks

    def __init__(
        self,
        epoch: int = 10000,
        pop_size: int = 100,
        max_sparks: int = 100,
        p_a: float = 0.04,
        p_b: float = 0.8,
        max_ea: int = 40,
        m_sparks: int = 100,
        *,
        name: str | None = None,
        mode: str | None = None,
    ) -> None:
        """
        Args:
            epoch (int): maximum number of iterations, default = 10000
            pop_size (int): number of population size, default = 100
            max_sparks (int): parameter controlling the total number of sparks generated by the pop_size fireworks, default=100
            p_a (float): percent (const parameter), default=0.04
            p_b (float): percent (const parameter), default=0.8
            max_ea (int): maximum explosion amplitude, default=40
            m_sparks (int): number of sparks generated in each explosion generation, default=100
        """
        LegacyNativeOptimizer.__init__(
            self,
            parameters=["epoch", "pop_size", "max_sparks", "p_a", "p_b", "max_ea", "m_sparks"],
            sort_flag=False,
            parallelizable=True,
            name=name,
            mode=mode,
        )
        self.epoch = cy.validator(int, epoch, [1, 100000], "epoch")
        self.pop_size = cy.validator(int, pop_size, [5, 10000], "pop_size")
        self.max_sparks = cy.validator(int, max_sparks, [2, 10000], "max_sparks")
        self.p_a = cy.validator(float, p_a, (0, 1.0), "p_a")
        self.p_b = cy.validator(float, p_b, (0, 1.0), "p_b")
        self.max_ea = cy.validator(int, max_ea, [2, 100], "max_ea")
        self.m_sparks = cy.validator(int, m_sparks, [2, 10000], "m_sparks")

    cdef void evolve(self, int epoch_c):
        cdef NativePopulation pop = self.pop
        cdef NativePopulation sparks, both
        cdef Py_ssize_t n = pop.n, d = pop.d
        cdef object rng = self.generator
        X = np.array(pop.X)
        lb, ub = self.problem.lb, self.problem.ub
        fit = np.array(pop.F)
        fl = np.sort(fit)
        si = self.max_sparks * (fl[-1] - fit) / (n * fl[-1] - np.sum(fl) + self.EPSILON)
        Ai = self.max_ea * (fit - fl[0]) / (np.sum(fl) - fl[0] + self.EPSILON)
        n_sparks = np.where(si < self.p_a * self.max_sparks, int(round(self.p_a * self.max_sparks) + 1),
                            np.where(si > self.p_b * self.m_sparks, int(round(self.p_b * self.max_sparks) + 1),
                                     np.round(si).astype(int) + 1))
        parent = np.concatenate([np.repeat(np.arange(n), n_sparks), rng.integers(0, n, size=self.m_sparks)])
        total, k = len(parent), len(parent) - self.m_sparks
        # every spark shifts a random subset of the dimensions of its firework
        subset = self.generator.random((total, d)).argsort(axis=1).argsort(axis=1) < np.round(rng.uniform(size=total) * d)[:, None]
        shift = np.empty((total, d))
        shift[:k] = (Ai[parent[:k]] * rng.uniform(-1, 1, size=k))[:, None]  # explosion sparks
        shift[k:] = rng.normal(0, 1, (self.m_sparks, d))  # gaussian sparks
        pos = X[parent] + np.where(subset, shift, 0.0)
        pos = np.where((pos < lb) | (pos > ub), lb + np.abs(pos) % (ub - lb), pos)
        sparks = pop.take(np.zeros(total, dtype=int))
        sparks.X[:] = self.correct_solution(pos)
        self.evaluate(sparks, 0, total)
        both = sparks.concat(pop)
        self.pop = both.take(self.sorted_order(both)[:self.pop_size])
